# Generated by Django 3.0.6 on 2020-05-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=200, unique=True)),
                ('imageUrl', models.FileField(blank=True, db_column='image_url', null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'MyModel',
                'managed': True,
            },
        ),
    ]
